spring:
  application:
    name: chess

  datasource:
    url: jdbc:postgresql://localhost:5432/chess
    username: postgres_user
    password: postgres_password

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379